server:
  port: 0
spring:
  kafka:
    bootstrap-servers: localhost:9092  # 必配
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

dubbo:
  application:
    name: user-provider
  consumer:
    check: false  # 启动时不检查服务提供者
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 0